"""Initial migration

Revision ID: aed324d91a2c
Revises: 
Create Date: 2024-03-11 13:18:22.432797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed324d91a2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_stock', schema=None) as batch_op:
        batch_op.drop_column('data')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
